# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 946d565472ee537c5c74f3d060a84f1149fef37f358f117fe1cdc409a827f402573da64d4252497a19288de8556567b3c7d1ab061d41ec705b04605999a1df38

test:
  secret_key_base: 1cc8f200262a2cc8a61e833a0f73d48b66bb73fcf3cb27ab8b3c329483e3a8b5d74f502038f996c6a735bff67fa3d0efd6fc865009c413578987e9595b0460a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
